POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1YTkyZTYzNTVmNzIyYjIzOTI5NTE2MWYiLCJpYXQiOjE1MTk1NzY2ODR9.yJWu7M8F_6XoNF-bO9JgKGMB-OvS54n6k97h9NNZBs4

{
    "title": "Test Title",
    "author": "Test Author",
    "url": "Test Url",
    "likes": 0
}